# OpenAI API
openai:
    key_path: 'assets/openai/premium_key2.txt'

# OCR Model
vietocr:
    device: 'cuda:0'

ocr_correction:
    weight_path: 'VietnameseOcrCorrection/weights/seq2seq_0.pth'
    model_type: 'seq2seq'
    device: 'cuda:0'
    
# Prompt configs
prompt:
    correction: 'assets/promts/correction_prompt.txt'
    extraction: 'assets/promts/extraction_prompt.txt'
    
# Parameters
process:
    box_padding:
        w: 0 # px
        h: 2 # px